### ISSUE TITLE
Failed tests in coauthor feature

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#83]
Three tests are failing, with different error messages depending on which other changes have been merged.

Failures:

  1) coauthor abby shares work @ included
     Failure/Error: expect(page).to have_content( user.email )
       expected to find text "dit.application.test@ualberta.ca" in "Hydra North click for notifications. click for archivist1@example.com dashboard Home About Help Contact Search Sufia Go All × The file little_file.txt has been updated. My DashboardMy FilesBrowse View Edit little_file.txt Descriptions Versions Permissions Permissions Visibility - who should have the ability to read and download Open Access Visible to the world. University of Alberta Visible to all University of Alberta users. Embargo Restricted to until then Private Visible to users/groups specified below, if any. Share With (optional) Enter Account Label (one at a time)Use the add button to give access to one Account Label at a time (it will be added to the list below). Select the user, by name or Account Label. Then select the access level you wish to grant and click on Add this Account Label to complete adding the permission.Account Label (without the @ualberta.ca part) Search for a user Account Label (without the @ualberta.ca part)Access type to grantAdd this Account Label Use the add button to give access to one group at a time (it will be added to the list below).GroupAccess type to grantAdd this group Person/Group Access Level Depositor (archivist1@example.com) Edit Save A service of Project Hydra. v.6.0.0.rc1 Copyright © 2013 Project Hydra Licensed under the Apache License, Version 2.0 Background image courtesy of Penn State University"
     # ./spec/features/coauthor_spec.rb:74:in `share_work_with'
     # ./spec/features/coauthor_spec.rb:34:in `block (3 levels) in <top (required)>'

  2) coauthor abby shares work @ not included
     Failure/Error: expect(page).to have_content( user.email )
       expected to find text "dit.application.test@ualberta.ca" in "Hydra North click for notifications. click for archivist1@example.com dashboard Home About Help Contact Search Sufia Go All × The file little_file.txt has been updated. My DashboardMy FilesBrowse View Edit little_file.txt Descriptions Versions Permissions Permissions Visibility - who should have the ability to read and download Open Access Visible to the world. University of Alberta Visible to all University of Alberta users. Embargo Restricted to until then Private Visible to users/groups specified below, if any. Share With (optional) Enter Account Label (one at a time)Use the add button to give access to one Account Label at a time (it will be added to the list below). Select the user, by name or Account Label. Then select the access level you wish to grant and click on Add this Account Label to complete adding the permission.Account Label (without the @ualberta.ca part) Search for a user Account Label (without the @ualberta.ca part)Access type to grantAdd this Account Label Use the add button to give access to one group at a time (it will be added to the list below).GroupAccess type to grantAdd this group Person/Group Access Level Depositor (archivist1@example.com) Edit Save A service of Project Hydra. v.6.0.0.rc1 Copyright © 2013 Project Hydra Licensed under the Apache License, Version 2.0 Background image courtesy of Penn State University"
     # ./spec/features/coauthor_spec.rb:74:in `share_work_with'
     # ./spec/features/coauthor_spec.rb:38:in `block (3 levels) in <top (required)>'

  3) coauthor abby shares work barbara can edit and feature
     Failure/Error: expect(page).to have_content( user.email )
       expected to find text "dit.application.test@ualberta.ca" in "Hydra North click for notifications. click for archivist1@example.com dashboard Home About Help Contact Search Sufia Go All × The file little_file.txt has been updated. My DashboardMy FilesBrowse View Edit little_file.txt Descriptions Versions Permissions Permissions Visibility - who should have the ability to read and download Open Access Visible to the world. University of Alberta Visible to all University of Alberta users. Embargo Restricted to until then Private Visible to users/groups specified below, if any. Share With (optional) Enter Account Label (one at a time)Use the add button to give access to one Account Label at a time (it will be added to the list below). Select the user, by name or Account Label. Then select the access level you wish to grant and click on Add this Account Label to complete adding the permission.Account Label (without the @ualberta.ca part) Search for a user Account Label (without the @ualberta.ca part)Access type to grantAdd this Account Label Use the add button to give access to one group at a time (it will be added to the list below).GroupAccess type to grantAdd this group Person/Group Access Level Depositor (archivist1@example.com) Edit Save A service of Project Hydra. v.6.0.0.rc1 Copyright © 2013 Project Hydra Licensed under the Apache License, Version 2.0 Background image courtesy of Penn State University"
     # ./spec/features/coauthor_spec.rb:74:in `share_work_with'
     # ./spec/features/coauthor_spec.rb:50:in `block (3 levels) in <top (required)>'

Finished in 2 minutes 47.4 seconds (files took 7.82 seconds to load)
16 examples, 3 failures

Failed examples:

rspec ./spec/features/coauthor_spec.rb:32 # coauthor abby shares work @ included
rspec ./spec/features/coauthor_spec.rb:36 # coauthor abby shares work @ not included
rspec ./spec/features/coauthor_spec.rb:48 # coauthor abby shares work barbara can edit and feature

---------------

weiweishi commented 27 minutes ago

Checked out the commit prior to the embargo merge :17b32e93800ae2d7ed36229ef0fcea7e39966e50
The same three tests still failed but with different error message this time:

1) coauthor abby shares work @ included
Failure/Error: click_link "Permissions"
Capybara::ElementNotFound:
Unable to find link "Permissions"
# ./spec/features/coauthor_spec.rb:73:in share_work_with' # ./spec/features/coauthor_spec.rb:34:inblock (3 levels) in '

2) coauthor abby shares work @ not included
Failure/Error: click_link "Permissions"
Capybara::ElementNotFound:
Unable to find link "Permissions"
# ./spec/features/coauthor_spec.rb:73:in share_work_with' # ./spec/features/coauthor_spec.rb:38:inblock (3 levels) in '

3) coauthor abby shares work barbara can edit and feature
Failure/Error: click_link "Permissions"
Capybara::ElementNotFound:
Unable to find link "Permissions"
# ./spec/features/coauthor_spec.rb:73:in share_work_with' # ./spec/features/coauthor_spec.rb:50:inblock (3 levels) in '
Closed with unmerged commits

**Comment by pgwillia** [comment]
Early indication is that these tests fail because the rights field is required but no value is given and default is no longer assigned.

**Comment by pgwillia** [comment]
I'm seeing 3 failures with this message:

 1) coauthor abby shares work @ included
     Failure/Error: expect(page).to have_content( user.email )
       expected to find text "dit.application.test@ualberta.ca" in 

I can confirm that the application is not saving 'Share With' values.  See this message in the log
```Unpermitted parameters: permissions_attributes```

**Comment by pgwillia** [comment]
See this failure with [vanilla with sufia 6 rc2](https://gist.github.com/pgwillia/b1e48eff57d65fa82a73) as well.  Confirmed fixed in sufia 6 rc3.  Tried to upgrade HydraNorth to use sufia 6 rc3 but encountered many errors, notably [#874](https://github.com/projecthydra/sufia/issues/874).

Holding until sufia 6.0.0 is released for real.

**Comment by pgwillia** [comment]
I've isolated the failing tests to the introduction of embargo in #66.  I can see that the reason for the failure is that ```generic_file.attributes = attributes``` isn't assigned in app/actors/hydranorth/generic_file/actor.rb#update_metadata.  

I think that update_metadata should remain the same and update_visibility should be overridden to include a call to interpret_visibility.  This fixes the coauthor tests but embargo feature tested through the ui (should really write a feature spec for this) now failing at https://github.com/projecthydra/hydra-head/blob/master/hydra-access-controls/app/models/concerns/hydra/access_controls/visibility.rb#L17 because Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_EMBARGO isn't permitted.

@weiweishi shall we put our heads together on this?

**Comment by weiweishi** [comment]
I remember the tests were still failing with a commit prior to the embargo
PR? Let's look at the code together.

Weiwei

，pgwillia <notifications@github.com> ：

I've isolated the failing tests to the introduction of embargo in #66
<https://github.com/ualbertalib/HydraNorth/pull/66>. I can see that the
reason for the failure is that generic_file.attributes = attributes isn't
assigned in app/actors/hydranorth/generic_file/actor.rb#update_metadata.

I think that update_metadata should remain the same and update_visibility
should be overridden to include a call to interpret_visibility. This fixes
the coauthor tests but embargo feature tested through the ui (should really
write a feature spec for this) now failing at
https://github.com/projecthydra/hydra-head/blob/master/hydra-access-controls/app/models/concerns/hydra/access_controls/visibility.rb#L17
because Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_EMBARGO
isn't permitted.

@weiweishi <https://github.com/weiweishi> shall we put our heads together
on this?

—
Reply to this email directly or view it on GitHub
<https://github.com/ualbertalib/HydraNorth/issues/83#issuecomment-76081753>.
